services:
  - type: web
    name: pneumonia-detection
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --timeout 120 app:app
    healthCheckPath: /healthz
